version: '3.5'
services:

  mongodb:
    image: mongo
    restart: always
    container_name: mongo_db
    ports:
      - 27017:27017

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    # volumes:
    #   - /home/gerardo/Escritorio/PROYECTOS/PROPIOS/hotel_america/hotel_america_backend/data/:/data/db